import { formatFecha } from "@shared/utils/formatters";

const fmtNum = (v) => (v == null || v === "" ? "" : Number(v).toLocaleString("es-MX", { maximumFractionDigits: 4 }));
const fmtMoney = (v) => (v == null || v === "" ? "" : Number(v).toLocaleString("es-MX", { style: "currency", currency: "MXN" }));

export const SECCIONES_CICLO_ENGORDA = [
  {
    id: "calendario",
    label: "Calendario",
    dataKey: "calendario",
    exportNombre: "calendario_ciclo_engorda",
    searchKeys: ["tipo_evento", "actividad", "producto", "responsable", "estado_evento"],
    columns: [
      { header: "Fecha", key: "fecha", render: (r) => formatFecha(r.fecha) },
      { header: "Día ciclo", key: "dia_ciclo" },
      { header: "Tipo evento", key: "tipo_evento" },
      { header: "Actividad", key: "actividad" },
      { header: "Producto", key: "producto" },
      { header: "Estado", key: "estado_evento" },
      { header: "Observaciones", key: "observaciones" },
    ],
    fields: [
      { name: "fecha", label: "Fecha", type: "date" },
      { name: "tipo_evento", label: "Tipo evento", type: "text", required: true },
      { name: "actividad", label: "Actividad", type: "text", required: true },
      { name: "producto", label: "Producto/Alimento", type: "text" },
      { name: "dosis", label: "Dosis/Cantidad", type: "text" },
      { name: "responsable", label: "Responsable", type: "text" },
      { name: "estado_evento", label: "Estado", type: "select", options: ["Pendiente", "Realizado", "Reprogramado", "Cancelado"], default: "Pendiente" },
      { name: "observaciones", label: "Observaciones", type: "text", multiline: true },
    ],
  },
  {
    id: "gastos",
    label: "Gastos",
    dataKey: "gastos",
    exportNombre: "gastos_ciclo_engorda",
    searchKeys: ["categoria", "descripcion", "proveedor", "metodo_pago"],
    columns: [
      { header: "Fecha", key: "fecha", render: (r) => formatFecha(r.fecha) },
      { header: "Categoría", key: "categoria" },
      { header: "Cantidad", key: "cantidad", render: (r) => fmtNum(r.cantidad) },
      { header: "Unidad", key: "unidad" },
      { header: "Descripción", key: "descripcion" },
      { header: "Proveedor", key: "proveedor" },
      { header: "P. unitario", key: "precio_unitario", render: (r) => fmtMoney(r.precio_unitario) },
      { header: "Importe", key: "importe_final", render: (r) => fmtMoney(r.importe_final) },
      { header: "Pago", key: "metodo_pago" },
    ],
    fields: [
      { name: "fecha", label: "Fecha gasto", type: "date", required: true },
      { name: "categoria", label: "Categoría", type: "text", required: true },
      { name: "cantidad", label: "Cantidad", type: "number", required: true },
      { name: "unidad", label: "Unidad", type: "text", required: true, default: "kg" },
      { name: "descripcion", label: "Descripción", type: "text" },
      { name: "proveedor", label: "Proveedor", type: "text" },
      { name: "precio_unitario", label: "Precio unitario", type: "number", required: true },
      { name: "importe_final", label: "Importe final", type: "number" },
      { name: "metodo_pago", label: "Método de pago", type: "text" },
      { name: "observaciones", label: "Observaciones", type: "text", multiline: true },
    ],
  },
  {
    id: "ventas",
    label: "Ventas",
    dataKey: "ventas",
    exportNombre: "ventas_ciclo_engorda",
    searchKeys: ["producto", "cliente", "estado_pago"],
    columns: [
      { header: "Fecha", key: "fecha", render: (r) => formatFecha(r.fecha) },
      { header: "Producto", key: "producto" },
      { header: "Cantidad", key: "cantidad", render: (r) => fmtNum(r.cantidad) },
      { header: "Unidad", key: "unidad" },
      { header: "Cliente", key: "cliente" },
      { header: "P. unitario", key: "precio_unitario", render: (r) => fmtMoney(r.precio_unitario) },
      { header: "Importe", key: "importe_final", render: (r) => fmtMoney(r.importe_final) },
      { header: "Estado pago", key: "estado_pago" },
    ],
    fields: [
      { name: "fecha", label: "Fecha venta", type: "date", required: true },
      { name: "producto", label: "Producto", type: "text", required: true },
      { name: "cantidad", label: "Cantidad", type: "number", required: true },
      { name: "unidad", label: "Unidad", type: "text", required: true },
      { name: "cliente", label: "Cliente", type: "text" },
      { name: "precio_unitario", label: "Precio unitario", type: "number", required: true },
      { name: "importe_final", label: "Importe final", type: "number" },
      { name: "estado_pago", label: "Estado de pago", type: "select", options: ["Pagado", "Pendiente", "Parcial", "Crédito", "Cancelado"] },
      { name: "observaciones", label: "Observaciones", type: "text", multiline: true },
    ],
  },
  {
    id: "biometrias",
    label: "Biometrías",
    dataKey: "biometrias",
    exportNombre: "biometrias_ciclo_engorda",
    searchKeys: ["observaciones"],
    columns: [
      { header: "Fecha", key: "fecha", render: (r) => formatFecha(r.fecha) },
      { header: "Día ciclo", key: "dia_ciclo" },
      { header: "Animales pesados", key: "animales_pesados" },
      { header: "Peso prom. (g)", key: "peso_promedio_g", render: (r) => fmtNum(r.peso_promedio_g) },
      { header: "GDP g/día", key: "indice_crecimiento_g_dia", render: (r) => fmtNum(r.indice_crecimiento_g_dia) },
      { header: "Ganancia última (g)", key: "ganancia_ultima_g", render: (r) => fmtNum(r.ganancia_ultima_g) },
    ],
    fields: [
      { name: "fecha", label: "Fecha biometría", type: "date", required: true },
      { name: "animales_pesados", label: "Animales pesados", type: "number" },
      { name: "peso_promedio_g", label: "Peso promedio (g)", type: "number", required: true },
      { name: "observaciones", label: "Observaciones", type: "text", multiline: true },
    ],
  },
  {
    id: "mortalidad",
    label: "Mortalidad",
    dataKey: "mortalidad",
    exportNombre: "mortalidad_ciclo_engorda",
    searchKeys: ["causa", "responsable", "accion_correctiva"],
    columns: [
      { header: "Fecha", key: "fecha", render: (r) => formatFecha(r.fecha) },
      { header: "Día ciclo", key: "dia_ciclo" },
      { header: "Muertes", key: "muertes" },
      { header: "Descartes", key: "descartes" },
      { header: "Causa", key: "causa" },
      { header: "Acción correctiva", key: "accion_correctiva" },
      { header: "Responsable", key: "responsable" },
    ],
    fields: [
      { name: "fecha", label: "Fecha", type: "date", required: true },
      { name: "muertes", label: "Muertes", type: "number", default: "0" },
      { name: "descartes", label: "Descartes", type: "number", default: "0" },
      { name: "causa", label: "Causa", type: "text" },
      { name: "accion_correctiva", label: "Acción correctiva", type: "text" },
      { name: "responsable", label: "Responsable", type: "text" },
      { name: "observaciones", label: "Observaciones", type: "text", multiline: true },
    ],
  },
  {
    id: "alimento",
    label: "Alimento / fases",
    dataKey: "alimento_fases",
    exportNombre: "alimento_ciclo_engorda",
    searchKeys: ["fase_alimento", "producto"],
    columns: [
      { header: "Fecha", key: "fecha", render: (r) => formatFecha(r.fecha) },
      { header: "Día ciclo", key: "dia_ciclo" },
      { header: "Fase", key: "fase_alimento" },
      { header: "Producto", key: "producto" },
      { header: "Kg ingreso", key: "kg_ingreso", render: (r) => fmtNum(r.kg_ingreso) },
      { header: "Kg consumidos", key: "kg_consumidos", render: (r) => fmtNum(r.kg_consumidos) },
      { header: "Existencia final", key: "existencia_final", render: (r) => fmtNum(r.existencia_final) },
    ],
    fields: [
      { name: "fecha", label: "Fecha", type: "date", required: true },
      { name: "fase_alimento", label: "Fase/Alimento", type: "text" },
      { name: "producto", label: "Producto", type: "text" },
      { name: "kg_ingreso", label: "Kg ingreso", type: "number" },
      { name: "kg_consumidos", label: "Kg consumidos", type: "number" },
      { name: "existencia_final", label: "Existencia final", type: "number" },
      { name: "observaciones", label: "Observaciones", type: "text", multiline: true },
    ],
  },
  {
    id: "consumo-estimado",
    label: "Consumo estimado",
    dataKey: "consumo_estimado",
    exportNombre: "consumo_estimado_ciclo_engorda",
    searchKeys: ["rango_dias", "fase_alimento", "producto"],
    columns: [
      { header: "Semana", key: "semana" },
      { header: "Días", key: "rango_dias" },
      { header: "Fase", key: "fase_alimento" },
      { header: "Producto", key: "producto" },
      { header: "Cons. conjunto", key: "consumo_conjunto", render: (r) => fmtNum(r.consumo_conjunto) },
      { header: "Cons. acumulado", key: "consumo_acumulado", render: (r) => fmtNum(r.consumo_acumulado) },
      { header: "GDP", key: "gdp", render: (r) => fmtNum(r.gdp) },
      { header: "Conversión", key: "conversion", render: (r) => fmtNum(r.conversion) },
    ],
    fields: [
      { name: "semana", label: "Semana", type: "number", required: true },
      { name: "rango_dias", label: "Rango días", type: "text" },
      { name: "fase_alimento", label: "Fase/Alimento", type: "text" },
      { name: "producto", label: "Producto", type: "text" },
      { name: "kg_ingreso", label: "Kg ingreso", type: "number" },
      { name: "consumo_individual", label: "Consumo individual", type: "number" },
      { name: "consumo_conjunto", label: "Consumo conjunto", type: "number" },
      { name: "consumo_acumulado", label: "Consumo acumulado", type: "number" },
      { name: "gdp", label: "GDP", type: "number" },
      { name: "conversion", label: "Conversión", type: "number" },
      { name: "mortalidad_semanal", label: "Mortalidad semanal", type: "number" },
      { name: "mortalidad_acumulada", label: "Mortalidad acumulada", type: "number" },
    ],
  },
  {
    id: "sanidad",
    label: "Sanidad",
    dataKey: "sanidad",
    exportNombre: "sanidad_ciclo_engorda",
    searchKeys: ["tipo", "producto", "responsable"],
    columns: [
      { header: "Fecha", key: "fecha", render: (r) => formatFecha(r.fecha) },
      { header: "Día ciclo", key: "dia_ciclo" },
      { header: "Tipo", key: "tipo" },
      { header: "Producto", key: "producto" },
      { header: "Dosis", key: "dosis" },
      { header: "Vía", key: "via" },
      { header: "Responsable", key: "responsable" },
    ],
    fields: [
      { name: "fecha", label: "Fecha", type: "date" },
      { name: "tipo", label: "Tipo", type: "text", required: true },
      { name: "producto", label: "Producto", type: "text" },
      { name: "dosis", label: "Dosis", type: "text" },
      { name: "via", label: "Vía", type: "text" },
      { name: "responsable", label: "Responsable", type: "text" },
      { name: "observaciones", label: "Observaciones", type: "text", multiline: true },
    ],
  },
];

export function seccionToExportColumns(seccion) {
  return seccion.columns.map((col) => ({
    header: col.header,
    value: (row) => (col.render ? col.render(row) : row[col.key] ?? ""),
  }));
}
